package com.qktz.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
	
		arp.addMapping("large_capital_data", LargeCapitalData.class);
        arp.addMapping("china_stocks_vane", ChinaStockVaneModel.class);
		arp.addMapping("amoy_share_pool", AmoySharePool.class);
		arp.addMapping("master_stock", MasterStock.class);
		arp.addMapping("master_stock_pool", MasterStockPool.class);
		arp.addMapping("master_stock_pool_tmp", MasterStockPoolTmp.class);
		
		arp.addMapping("master_stock_pool_operator_flow", MasterStockPoolOperatorFlow.class);
		//portfolio
		arp.addMapping("portfolio_accountid", Account.class);
		arp.addMapping("portfolio_adviser", Adviser.class);
		arp.addMapping("portfolio", Portfolio.class);
		arp.addMapping("portfolio_yield", PortfolioYield.class);
		arp.addMapping("portfolio_industry", PortfolioIndustry.class);
		arp.addMapping("current_stocks", CurrentStocks.class);
		arp.addMapping("history_stocks", HistoryStocks.class);
		arp.addMapping("portfolio_deal", PortfolioDeal.class);
		arp.addMapping("latest_operation", LatestOperation.class);
		arp.addMapping("portfolio_operation_detail", OperationDetail.class);
		arp.addMapping("history_yield", HistoryYield.class);
		arp.addMapping("portfolio_deal_dynamics", PortfolioDealDynamics.class);
		arp.addMapping("portfolio_creator", PortfolioCreator.class);
	}
}

